import "./globals.css";
import { Inter } from "next/font/google";
import StoreProvider from "./StoreProvider";
import { Toaster } from "react-hot-toast";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en" className="h-full">
            <body className={inter.className}>
                <main className="min-h-screen bg-white">
                    <Navbar />
                    <Toaster />
                    <StoreProvider>{children}</StoreProvider>
                    <Footer />
                </main>
            </body>
        </html>
    );
}
