import { Inter } from "next/font/google";
import "./globals.css";
import StoreProvider from "./StoreProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en" className="h-full">
            <body className={inter.className}>
                <main className="h-[100vh] bg-white">
                    <StoreProvider>{children}</StoreProvider>
                </main>
            </body>
        </html>
    );
}
